[package]
name = "sunk"
version = "0.1.0"
authors = ["alex-smith <azphreal19@protonmail.com>"]

[dependencies]
failure = "0.1.1"
hyper = "0.11.14"
futures = "0.1.17"
tokio-core = "0.1.12"
serde = "1.0.27"
serde_json = "1.0.9"
md5 = "0.3.6"
rand = "0.4.2"

# md5 = { version = "0.3.6", optional = true }
# rand = { version = "0.4.2", optional = true }

# [features]
# default = ["secure"]

# secure = ["md5", "rand"]