[package]
name = "sunk"
version = "0.0.6"
authors = ["alex-smith <azphreal19@protonmail.com>"]
description = "Rust bindings for the Subsonic music streaming API"
homepage = "https://github.com/Azphreal/sunk"
repository = "https://github.com/Azphreal/sunk"
readme = "README.md"
keywords = ["subsonic", "airsonic", "music", "api", "webapi"]
categories = ["api-bindings"]
license = "Apache-2.0/MIT"
publish = false

[dependencies]
failure = "0.1.1"
log = "0.4.1"
md5 = "0.3.6"
rand = "0.4.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
reqwest = "0.8.4"